"""create user and blog tables

Revision ID: 1034aba94620
Revises: b29c717a8aa2
Create Date: 2024-11-24 21:29:20.263608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1034aba94620'
down_revision = 'b29c717a8aa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
